### ISSUE TITLE
AppBinding: Use of the service reference

### ISSUE THREAD

**Issue by sbose78** [kmodules/custom-resources#18]
Hi Tamal,

Thanks for the good work!

I have a question regarding the AppBinding CRD:

https://github.com/kmodules/custom-resources/blob/master/apis/appcatalog/v1alpha1/appbinding_types.go#L94

Why are you specifying the 'in-depth' service information instead of just specifying the name of the service?  The consuming party could look up the rest based on the `service` object ?

**Comment by sbose78** [comment]
@tamalsaha .

**Comment by tamalsaha** [comment]
Service could have multiple ports and this will specify the port intended to be used for client connection.
